# URL
@url=http://localhost:8000

### -------------------------------------
# Principal 

###
# (PING) Verificar aplicação web
GET {{url}}

### -------------------------------------
# cliente 

###
# URL base para a api de clientes
@apiCliente={{url}}/api/cliente

###
# Cadastra/salva um novo cliente
POST {{apiCliente}}

{
    "nome": "Maria",
    "email": "maria@gmail.com"
}




# URL base para a api de endereco
@apiEndereco={{url}}/endereco/maria@gmail.com

###
# Cadastra/salva um novo Endereço
POST {{apiEndereco}}

{
    "email": "maria@gmail.com",
    "rua": "Rua Afonso",
    "numero": 33,
    "cep": "20000000",
    "cidade": "Rio de Janeiro",
    "estado": "RJ"
}


   