### ************************************
# API carrinho_compras / decoracao
#

###
# URL
@url=http://localhost:8000

### -------------------------------------
# Principal 

###
# (PING) Verificar aplicação web
GET {{url}}

### -------------------------------------
