name: Push Container to Heroku

on:
  pull_request:
    type:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - name: Vesion
        id: Version
        uses: IIlyichev/github-tag-action@v6.3
        with:
          github_token: ${{ secrets.RELEASE_CI }}
          release_banches: main, release
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt update && sudo apt install heroku
          if [ -f requerimentos.txt ]; then pip install -r requerimentos.txt; fi
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          heroku container:push -a cart-backend web
          heroku container:release -a cart-backend web
