name: Test Suite

on: [push]

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets. DB_USER }}
  PASSWD: ${{ secrets.PASSWD }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requerimentos.txt ]; then pip install -r requerimentos.txt; fi
      - name: Dotenv create
        run: |
          echo ${{ env.DB_HOST }} >> .env
          echo ${{ env.DB_USER }} >> .env
          echo ${{ env.PASSWD }} >> .env
          echo ${{ env.DB_NAME }} >> .env
      - name: Test with pytest
        run: |
          pytest